# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448015c4f6c7726173912db92b02fc52f8ce74d773f514af4819f05f35147a69953c85e3badd37292400894d2ebf53963c85be52ff0e7ddb2415d1cbe0e155c8

test:
  secret_key_base: 702db26a86fe74f75d06f82a51730f6e829b5bc0236b8f8928e4ddcbea42bd9476e1bbb266df5ff16469a2629ebdb80bb51c97b4eb4ce6a824fc9585d20bb9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
